name: anyhoo_logging
description: "A package for logging."
version: 0.0.4
homepage: https://anyhoosolutions.web.app/documentation/flutter_platform_kit
publish_to: none

environment:
  sdk: ^3.10.0-290.4.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.26.3
  bloc_test: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
