name: anyhoo_core
description: Shared models and interfaces used across Anyhoo packages.
version: 0.0.14
publish_to: none
homepage: https://anyhoosolutions.web.app/documentation/flutter_platform_kit

environment:
  sdk: ^3.10.0-290.4.beta
  flutter: ">=1.17.0"

dependencies:
  bloc: ^9.1.0
  flutter:
    sdk: flutter
  flutter_launch_arguments: ^1.0.1
  freezed_annotation: ^3.1.0
  logging: ^1.3.0
  timezone: ^0.10.1

dev_dependencies:
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.3

flutter:
  uses-material-design: true
  generate: true
