name: anyhoo_auth
description: A flexible authentication package that supports custom user models using generics.
version: 0.0.28
publish_to: none
homepage: https://anyhoosolutions.web.app/documentation/flutter_platform_kit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  anyhoo_core:
    path: ../anyhoo_core
  anyhoo_logging:
    path: ../anyhoo_logging
  flutter_bloc: ^9.1.0
  firebase_auth: ^6.1.2
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  flutter_svg: ^2.2.2
  cloud_firestore: ^6.1.0
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  logging: ^1.3.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  build_runner: ^2.10.4
  flutter_lints: ^2.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
