name: anyhoo_router
description: "A new Flutter package project."
version: 0.0.1
homepage: https://anyhoosolutions.web.app/documentation/flutter_platform_kit
publish_to: none

environment:
  sdk: ^3.10.0-290.4.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.0
  logging: ^1.3.0
  anyhoo_auth:
    git:
      url: https://github.com/Anyhoosolutions/flutter_platform_kit.git
      path: packages/anyhoo_auth
      ref: main_0.0.5
  anyhoo_core:
    git:
      url: https://github.com/Anyhoosolutions/flutter_platform_kit.git
      path: packages/anyhoo_core
      ref: main_0.0.5
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
