name: anyhoo_app_bar
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.0-290.4.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
