name: anyhoo_app_bar
description: "A new Flutter package project."
version: 0.0.7
homepage: https://anyhoosolutions.web.app/documentation/flutter_platform_kit
publish_to: none

environment:
  sdk: ^3.10.0-290.4.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  anyhoo_shimmer:
    path: ../anyhoo_shimmer
  anyhoo_router:
    path: ../anyhoo_router
  go_router: ^17.0.0
  logging: ^1.3.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.3

flutter:
  generate: true
  uses-material-design: true
