name: widgetbook_workspace
description: "A workspace for widgetbook apps."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.20.0
  widgetbook_annotation: ^3.9.0
  mocktail: ^1.0.4
  device_frame_plus: ^1.0.0
  image: ^4.5.4
  cross_file: ^0.3.4+2

  image_selector:
    path: ../packages/image_selector

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  widgetbook_generator: ^3.20.0
  build_runner: ^2.10.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
