name: anyhoo_remote_config
description: "A package for managing remote config in a Flutter app."
version: 0.0.3
homepage: https://github.com/anyhoosolutions/flutter_platform_kit/tree/main/packages/anyhoo_remote_config
publish_to: none

environment:
  sdk: ^3.10.0-290.4.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_remote_config: ^6.1.2
  logging: ^1.3.0
  bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
