name: anyhoo_firebase
description: "A new Flutter package project."
version: 0.0.10
homepage: https://anyhoosolutions.web.app/documentation/flutter_platform_kit
publish_to: none

environment:
  sdk: ^3.10.0-290.4.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  firebase_crashlytics: ^5.0.5
  logging: ^1.3.0
  anyhoo_core:
    path: ../anyhoo_core
  firebase_analytics: ^12.0.4
  firebase_remote_config: ^6.1.2
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  mocktail: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
