name: example_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Anyhoo packages
  anyhoo_core:
    path: ../packages/anyhoo_core
  anyhoo_auth:
    path: ../packages/anyhoo_auth
  anyhoo_image_selector:
    path: ../packages/anyhoo_image_selector
  anyhoo_firebase:
    path: ../packages/anyhoo_firebase
  anyhoo_router:
    path: ../packages/anyhoo_router
  anyhoo_remote_config:
    path: ../packages/anyhoo_remote_config
  anyhoo_shimmer:
    path: ../packages/anyhoo_shimmer
  anyhoo_logging:
    path: ../packages/anyhoo_logging
  anyhoo_map:
    path: ../packages/anyhoo_map

  # Required dependencies
  flutter_bloc: ^9.1.0
  logging: ^1.3.0
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  go_router: ^17.0.0
  build_runner: ^2.10.4
  go_router_builder: ^4.1.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
