name: freezed_to_ts
description: A script to convert Dart freezed classes to TypeScript interfaces.
version: 0.0.11
homepage: https://github.com/lidholm/flutter_platform_kit/tree/main/tools/freezed_to_ts
repository: https://github.com/lidholm/flutter_platform_kit
environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  freezed_to_ts: freezed_to_ts
  copy_shared_models_to_docs: copy_shared_models_to_docs

dependencies:
  analyzer: ^6.4.1
  args: ^2.5.0
  freezed_annotation: ^2.4.1
  logging: ^1.3.0
  path: ^1.9.0

dev_dependencies:
  test: ^1.25.2
