name: sentry_cli
description: A CLI tool for querying Sentry issues.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.0
  http: ^1.2.0

dev_dependencies:
  lints: ^4.0.0
