name: Verify documentation

on:
  pull_request:
    branches:
      - main

jobs:
  verify-docs:
    name: Verify documentation is up-to-date
    runs-on: ubuntu-latest

    # Skip if PR title contains "WIP"
    if: ${{ !contains(github.event.pull_request.title, 'WIP') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify documentation
        uses: ./.github/actions/verify_docs
